spring:
  datasource:
    url: jdbc:mysql://localhost:3306/scm_db
    username: root
    password: dongyang
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    show_sql: true
    format-sql: true

  jwt:
    expiration_time: 86400000 #1?
    secret: fgrohegRGHIEOVNLDREfklgRGf23534tfjhdfuioewohidffhhgs357GFHDRHSRT56erHertggerhrghRTHEYR568654kjfthtrdrthgfGHR3564u553yDHSRTHrtsrfgsrtsd

logging:
  level:
    org.hibernate: WARN
    org.hibernate.orm.connections.pooling: WARN

server:
  port: 8003

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true

  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /api/**